### ISSUE TITLE
ARCH_CONTEXT_SIZE undefined

### ISSUE THREAD

**Issue by dzavalishin** [sergev/uos-embedded#17]
Compiling for atmega:

```
P:/uos-embedded//sources/kernel/internal.h: In function 'mutex_check_pended_irq':
P:/uos-embedded//sources/kernel/internal.h:267: error: cast to pointer from integer of different size
P:/uos-embedded//sources/kernel/internal.h: In function 'task_stack_enough':
P:/uos-embedded//sources/kernel/internal.h:359: error: 'task_t' has no member named 'stack_limit'
P:/uos-embedded//sources/kernel/internal.h:360: error: 'ARCH_CONTEXT_SIZE' undeclared (first use in this function)
P:/uos-embedded//sources/kernel/internal.h:360: error: (Each undeclared identifier is reported only once
P:/uos-embedded//sources/kernel/internal.h:360: error: for each function it appears in.)
P:/uos-embedded//sources/kernel/internal.h:360: error: 'ARCH_ISR_FSPACE' undeclared (first use in this function)
```

Looking through sources found ARCH_CONTEXT_SIZE just in MIPS srcs. Compile is broken for the rest of architectures?

**Comment by vatilin** [comment]
Да, произошёл такой казус, что версию, специализированную под MIPS накатили
в основную ветку master.
Предыдущая версия, которая компилировалась под разные архитектуры,
продолжается в ветке stable.

Yes, there was an incident, the version specialized for MIPS was put into
'master' branch.
The previous version that is well compiled for different architectures is
now supported in 'stable' branch.


чт, 31 янв. 2019 г. в 21:50, Dmitry Zavalishin <notifications@github.com>:

**Comment by dzavalishin** [comment]
thanx

**Comment by aol-nnov** [comment]
>  there was an incident

@vatilin should not it be mentioned somewhere with large red bold font?!

Just spent the whole day fighting master branch for arm cpu. Real bummer, guys!

If project is abandoned or turned into MIPS-only, please state that too!

**Comment by sergev** [comment]
> should not it be mentioned somewhere with large red bold font?!
> Just spent the whole day fighting master branch for arm cpu. Real bummer, guys!

Looks like it was a bad idea to use the master branch for experimental development.  The instability was caused mostly by alexrayne's changes.  So I've renamed old master as 'lityagin', and installed 'stable' as new master. I hope this helps to reduce confusion.

**Comment by aol-nnov** [comment]
@sergev setting `stable` as the default branch (in repo settings) will reduce the confusion even more! :)
